#! English
# The above comment sets the language for Ryp to be rendered in.
# It does not change the language of any of the configs.
# The language of the configs cannot be changed, it's a security thing of being
# able to read what the config file will do.

# Background is the color behind the actual text... The background!
[sidebar.color.background]
active = "#EE7101"
inactive = "#808080"

[sidebar.color.foreground]
active = "#EE7101"
inactive = "#FFFFFF"

[sidebar.keybinds]
previous = "Ctrl+A"
next = "Ctrl+D"
toggle = "Ctrl+B"

[tab.color.active]
background = "#EE7101"
foreground = "#EE7101"

[tab.color.inactive]
background = "#808080"
foreground = "#FFFFFF"

[tab.keybinds]
left = "Ctrl+A"
right = "Ctrl+D"
close = "Ctrl+W"

[editor]
background = "#323232"
tab_size = 4

[plugins.console]
character = "λ"
toggle = "Ctrl+E"
color = "#BF00FF"

[saving]
on = true
time = 30_000
keybind = "Ctrl+S"

[selection.highlighting]
foreground = "#000000"
background = "#0084FF"

[search.highlighting.selected]
background = "#FFFF00"
foreground = "#000000"

[search.highlighting.unselected]
background = "#00FFFF"
foreground = "#FFFFFF"

[git.keybinds]
refresh = "Ctrl+G"
# These are left empty on purpose, they have no default binding
push = ""
pull = ""
new_repo = "Ctrl+Alt+N"
