#! English
# The above comment sets the language for Ryp to be rendered in.
# It does not change the language of any of the configs.
# The language of the configs cannot be changed, it's a security thing of being
# able to read what the config file will do.
#
# Rather than having something like...
# [ryp]
# language = "English"
# We make it so that you don't need to know how to say "language" in English!

# These are profiles, they allow further seperation and customization between GUI, TUI, moods, or users!
[[profile]]
name = "default"
extends = "default" # This is telling Ryp, "I've provivided EVERYTHING"
                    # If you haven't actually, Ryp will crash

[[profile]]
name = "gui"        # What to call the profile
extends = "default" # What to get anything not filled in from

[[profile]]
name = "tui"
extends = "default"


[default.sidebar]
# Background is the color behind the actual text... The background!
color.background = { active = "#EE7101", inactive = "#808080" }
# This sets the color of the font
color.foreground = { active = "#EE7101", inactive = "#FFFFFF" }
# Keybinds to interact with the sidebar
keybinds         = { previous = "Ctrl+A", next = "Ctrl+D", toggle = "Ctrl+B" }

[default.tab]
# Color of the currently active tab
color.active   = { background = "#EE7101", foreground = "#EE7101" }
# Color of inactive tabs
color.inactive = { background = "#808080", foreground = "#FFFFFF" }
# Keybinds to interact with the editor
keybinds       = { left = "Ctrl+A", right = "Ctrl+D", close = "Ctrl+W" }

# General settings for the editor
[default.editor]
background = "#323232"
tab_size   = 4

# The console that plugins print to
# `character` sets the character before every print
[default.plugins.console]
character = "λ"
toggle    = "Ctrl+E"
color     = "#BF00FF"

# Extra config stuff about saving
[default.saving]
on      = true
time    = 30_000
keybind = "Ctrl+S"

# These control the color the text is when doing a selection hilight (Shift+Arrow on TUI)
[default.selection]
highlighting = { foreground = "#000000", background = "#0084FF" }

[default.search.highlighting]
# This is the color the text is when doing a global search, for the item you're on
selected   = { background = "#FFFF00", foreground = "#000000" }
# The opposite of above, where instead of what you're on, what you're not on
unselected = { background = "#00FFFF", foreground = "#FFFFFF" }

# The keybinds to manage Git
[default.git.keybinds]
refresh  = "Ctrl+G"
new_repo = "Ctrl+Alt+N"
# These are left empty on purpose, they have no default binding
push     = ""
pull     = ""
