use hashbrown::HashMap;
use crate::app::langs::Languages;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum SettingsStrings {
    Sidebar,
    Color,
    Next,
    Previous,
    Tab,
    Editor,
    Active,
    Inactive,
    Background,
    Foreground,
    Keybinds,
    Help,
    Toggle,
    Close,
    Plugin,
    Console,
    On,
    Time,
    Saving,
    Selection,
    Highlighting,
}

pub fn build_settings_map(lang_setting: Languages) -> HashMap<SettingsStrings, &'static str> {
    match lang_setting {
        Languages::FRFrench => HashMap::from([
            (SettingsStrings::Sidebar, "barre_latérale"),
            (SettingsStrings::Color, "couleur"),
            (SettingsStrings::Next, "suivant"),
            (SettingsStrings::Previous, "précédent"),
            (SettingsStrings::Tab, "onglet"),
            (SettingsStrings::Editor, "éditeur"),
            (SettingsStrings::Active, "actif"),
            (SettingsStrings::Inactive, "inactif"),
            (SettingsStrings::Background, "arrière_plan"),
            (SettingsStrings::Foreground, "premier_plan"),
            (SettingsStrings::Keybinds, "raccourcis"),
            (SettingsStrings::Help, "aide"),
            (SettingsStrings::Toggle, ""),
            (SettingsStrings::Close, ""),
            (SettingsStrings::Plugin, ""),
            (SettingsStrings::Console, ""),
        ]),
        Languages::CAFrench => HashMap::from([
            (SettingsStrings::Sidebar, "barre_latérale"),
            (SettingsStrings::Color, "couleur"),
            (SettingsStrings::Next, "suivant"),
            (SettingsStrings::Previous, "précédent"),
            (SettingsStrings::Tab, "onglet"),
            (SettingsStrings::Editor, "éditeur"),
            (SettingsStrings::Active, "actif"),
            (SettingsStrings::Inactive, "inactif"),
            (SettingsStrings::Background, "arrière_plan"),
            (SettingsStrings::Foreground, "premier_plan"),
            (SettingsStrings::Keybinds, "raccourcis"),
            (SettingsStrings::Help, "aide"),
            (SettingsStrings::Toggle, ""),
            (SettingsStrings::Close, ""),
            (SettingsStrings::Plugin, ""),
            (SettingsStrings::Console, ""),
        ]),
        Languages::English => HashMap::from([
            (SettingsStrings::Sidebar, "sidebar"),
            (SettingsStrings::Color, "color"),
            (SettingsStrings::Next, "next"),
            (SettingsStrings::Previous, "previous"),
            (SettingsStrings::Tab, "tab"),
            (SettingsStrings::Editor, "editor"),
            (SettingsStrings::Active, "active"),
            (SettingsStrings::Inactive, "inactive"),
            (SettingsStrings::Background, "background"),
            (SettingsStrings::Foreground, "foreground"),
            (SettingsStrings::Keybinds, "keybinds"),
            (SettingsStrings::Help, "help"),
            (SettingsStrings::Toggle, "toggle"),
            (SettingsStrings::Close, "close"),
            (SettingsStrings::Plugin, "plugin"),
            (SettingsStrings::Console, "console"),
        ]),
        Languages::UKEnglish => HashMap::from([
            (SettingsStrings::Sidebar, "sidebar"),
            (SettingsStrings::Color, "colour"),
            (SettingsStrings::Next, "next"),
            (SettingsStrings::Previous, "previous"),
            (SettingsStrings::Tab, "tab"),
            (SettingsStrings::Editor, "editor"),
            (SettingsStrings::Active, "active"),
            (SettingsStrings::Inactive, "inactive"),
            (SettingsStrings::Background, "background"),
            (SettingsStrings::Foreground, "foreground"),
            (SettingsStrings::Keybinds, "keybinds"),
            (SettingsStrings::Help, "help"),
            (SettingsStrings::Toggle, "toggle"),
            (SettingsStrings::Close, "close"),
            (SettingsStrings::Plugin, "plugin"),
            (SettingsStrings::Console, "console"),
        ]),
        Languages::Dutch => HashMap::from([
            (SettingsStrings::Sidebar, "zijbalk"),
            (SettingsStrings::Color, "kleur"),
            (SettingsStrings::Next, "volgende"),
            (SettingsStrings::Previous, "vorige"),
            (SettingsStrings::Tab, "tabblad"),
            (SettingsStrings::Editor, "editor"),
            (SettingsStrings::Active, "actief"),
            (SettingsStrings::Inactive, "inactief"),
            (SettingsStrings::Background, "achtergrond"),
            (SettingsStrings::Foreground, "voorgrond"),
            (SettingsStrings::Keybinds, "sneltoetsen"),
            (SettingsStrings::Help, "help"),
            (SettingsStrings::Toggle, ""),
            (SettingsStrings::Close, ""),
            (SettingsStrings::Plugin, ""),
            (SettingsStrings::Console, ""),
        ]),
        Languages::German => HashMap::from([
            (SettingsStrings::Sidebar, "seitenleiste"),
            (SettingsStrings::Color, "farbe"),
            (SettingsStrings::Next, "weiter"),
            (SettingsStrings::Previous, "zurück"),
            (SettingsStrings::Tab, "tab"),
            (SettingsStrings::Editor, "editor"),
            (SettingsStrings::Active, "aktiv"),
            (SettingsStrings::Inactive, "inaktiv"),
            (SettingsStrings::Background, "hintergrund"),
            (SettingsStrings::Foreground, "vordergrund"),
            (SettingsStrings::Keybinds, "tastenkombinationen"),
            (SettingsStrings::Help, "hilfe"),
        ]),
        Languages::Japanese => HashMap::from([
            (SettingsStrings::Sidebar, "サイドバー"),
            (SettingsStrings::Color, "カラー"),
            (SettingsStrings::Next, "次へ"),
            (SettingsStrings::Previous, "前へ"),
            (SettingsStrings::Tab, "タブ"),
            (SettingsStrings::Editor, "エディタ"),
            (SettingsStrings::Active, "有効"),
            (SettingsStrings::Inactive, "無効"),
            (SettingsStrings::Background, "背景"),
            (SettingsStrings::Foreground, "前景"),
            (SettingsStrings::Keybinds, "キーバインド"),
            (SettingsStrings::Help, "ヘルプ"),
            (SettingsStrings::Toggle, ""),
            (SettingsStrings::Close, ""),
            (SettingsStrings::Plugin, ""),
            (SettingsStrings::Console, ""),
        ]),
        Languages::Korean => HashMap::from([
            (SettingsStrings::Sidebar, "사이드바"),
            (SettingsStrings::Color, "색상"),
            (SettingsStrings::Next, "다음"),
            (SettingsStrings::Previous, "이전"),
            (SettingsStrings::Tab, "탭"),
            (SettingsStrings::Editor, "편집기"),
            (SettingsStrings::Active, "활성화"),
            (SettingsStrings::Inactive, "비활성화"),
            (SettingsStrings::Background, "배경색"),
            (SettingsStrings::Foreground, "전경색"),
            (SettingsStrings::Keybinds, "단축키"),
            (SettingsStrings::Help, "도움말"),
            (SettingsStrings::Toggle, ""),
            (SettingsStrings::Close, ""),
            (SettingsStrings::Plugin, ""),
            (SettingsStrings::Console, ""),
        ]),
        Languages::LolCat => HashMap::from([
            (SettingsStrings::Sidebar, "saidbar"),
            (SettingsStrings::Color, "colr"),
            (SettingsStrings::Next, "nixt"),
            (SettingsStrings::Previous, "b4"),
            (SettingsStrings::Tab, "tab"),
            (SettingsStrings::Editor, "writr"),
            (SettingsStrings::Active, "on"),
            (SettingsStrings::Inactive, "off"),
            (SettingsStrings::Background, "bak_grund"),
            (SettingsStrings::Foreground, "4grond"),
            (SettingsStrings::Keybinds, "buttonz"),
            (SettingsStrings::Help, "halp"),
            (SettingsStrings::Toggle, "aktivat"),
            (SettingsStrings::Close, "stop"),
            (SettingsStrings::Plugin, "plugen"),
            (SettingsStrings::Console, "konsule"),
        ]),
        Languages::MandarinSimple => HashMap::from([
            (SettingsStrings::Sidebar, "侧边栏"),
            (SettingsStrings::Color, "颜色"),
            (SettingsStrings::Next, "下一步"),
            (SettingsStrings::Previous, "上一步"),
            (SettingsStrings::Tab, "标签页"),
            (SettingsStrings::Editor, "编辑器"),
            (SettingsStrings::Active, "启用"),
            (SettingsStrings::Inactive, "禁用"),
            (SettingsStrings::Background, "背景"),
            (SettingsStrings::Foreground, "前景"),
            (SettingsStrings::Keybinds, "快捷键"),
            (SettingsStrings::Help, "帮助"),
            (SettingsStrings::Toggle, ""),
            (SettingsStrings::Close, ""),
            (SettingsStrings::Plugin, ""),
            (SettingsStrings::Console, ""),
        ]),
        Languages::MandarinTraditional => HashMap::from([
            (SettingsStrings::Sidebar, "側邊欄"),
            (SettingsStrings::Color, "顏色"),
            (SettingsStrings::Next, "下一步"),
            (SettingsStrings::Previous, "上一步"),
            (SettingsStrings::Tab, "標籤頁"),
            (SettingsStrings::Editor, "編譯器"),
            (SettingsStrings::Active, "啟用"),
            (SettingsStrings::Inactive, "禁用"),
            (SettingsStrings::Background, "背景"),
            (SettingsStrings::Foreground, "前景"),
            (SettingsStrings::Keybinds, "快捷鍵"),
            (SettingsStrings::Help, "幫助"),
            (SettingsStrings::Toggle, ""),
            (SettingsStrings::Close, ""),
            (SettingsStrings::Plugin, ""),
            (SettingsStrings::Console, ""),
        ]),
        Languages::Polish => HashMap::from([
            (SettingsStrings::Sidebar, "pasek_boczny"),
            (SettingsStrings::Color, "kolor"),
            (SettingsStrings::Next, "dalej"),
            (SettingsStrings::Previous, "wstecz"),
            (SettingsStrings::Tab, "karta"),
            (SettingsStrings::Editor, "edytor"),
            (SettingsStrings::Active, "aktywny"),
            (SettingsStrings::Inactive, "nieaktywny"),
            (SettingsStrings::Background, "tło"),
            (SettingsStrings::Foreground, "tekst"),
            (SettingsStrings::Keybinds, "skróty_klawiszowe"),
            (SettingsStrings::Help, "pomoc"),
            (SettingsStrings::Toggle, ""),
            (SettingsStrings::Close, ""),
            (SettingsStrings::Plugin, ""),
            (SettingsStrings::Console, ""),
        ]),
        Languages::Russian => HashMap::from([
            (SettingsStrings::Sidebar, "боковая_панель"),
            (SettingsStrings::Color, "цвет"),
            (SettingsStrings::Next, "след"),
            (SettingsStrings::Previous, "пред"),
            (SettingsStrings::Tab, "вкладка"),
            (SettingsStrings::Editor, "редактор"),
            (SettingsStrings::Active, "активен"),
            (SettingsStrings::Inactive, "неактивен"),
            (SettingsStrings::Background, "фон"),
            (SettingsStrings::Foreground, "текст"),
            (SettingsStrings::Keybinds, "горячие_клавиши"),
            (SettingsStrings::Help, "справка"),
            (SettingsStrings::Toggle, ""),
            (SettingsStrings::Close, ""),
            (SettingsStrings::Plugin, ""),
            (SettingsStrings::Console, ""),
        ]),
        Languages::Spanish => HashMap::from([
            (SettingsStrings::Sidebar, "barra_lateral"),
            (SettingsStrings::Color, "color"),
            (SettingsStrings::Next, "siguiente"),
            (SettingsStrings::Previous, "anterior"),
            (SettingsStrings::Tab, "pestaña"),
            (SettingsStrings::Editor, "editor"),
            (SettingsStrings::Active, "activo"),
            (SettingsStrings::Inactive, "inactivo"),
            (SettingsStrings::Background, "fondo"),
            (SettingsStrings::Foreground, "frente"),
            (SettingsStrings::Keybinds, "atajos"),
            (SettingsStrings::Help, "ayuda"),
            (SettingsStrings::Toggle, "cerrado"),
            (SettingsStrings::Close, "enchufa"),
            (SettingsStrings::Plugin, ""),
            (SettingsStrings::Console, "consola"),
        ]),
        Languages::Ukrainian => HashMap::from([
            (SettingsStrings::Sidebar, "бічна_панель"),
            (SettingsStrings::Color, "колір"),
            (SettingsStrings::Next, "далі"),
            (SettingsStrings::Previous, "назад"),
            (SettingsStrings::Tab, "вкладка"),
            (SettingsStrings::Editor, "редактор"),
            (SettingsStrings::Active, "активний"),
            (SettingsStrings::Inactive, "неактивний"),
            (SettingsStrings::Background, "фон"),
            (SettingsStrings::Foreground, "текст"),
            (SettingsStrings::Keybinds, "гарячі_клавіші"),
            (SettingsStrings::Help, "довідка"),
            (SettingsStrings::Toggle, ""),
            (SettingsStrings::Close, ""),
            (SettingsStrings::Plugin, ""),
            (SettingsStrings::Console, ""),
        ]),
    }
}
