#[derive(Debug, Clone, PartialEq)]
pub enum SidebarCategory {
    FileTree,
    Search,
    Git,
}

#[derive(Debug, Clone, PartialEq)]
pub enum Action {
    MoveUp(bool),
    MoveDown(bool),
    MoveLeft(bool),
    MoveRight(bool),
    PageUp(bool),
    PageDown(bool),
    InsertChar(char),
    InsertNewline,
    DeleteChar,
    Tab,
    OpenSearch,
    OpenReplace,
    OpenHelp,
    ToggleSidebar,
    SwitchFocus,
    Quit,
    ModalInsert(char),
    ModalDelete,
    ModalTab,
    ModalLeft,
    ModalRight,
    ModalUp,
    ModalDown,
    ModalConfirm,
    ModalConfirmForceNewTab,
    NextTab,
    PrevTab,
    CloseTab,
    CloseModal,
    SwitchSidebarCategory(SidebarCategory),
    NextSidebarCategory,
    PrevSidebarCategory,
    FocusFile(String, Option<usize>),
    SearchFiles(String),
    OpenNewFileModal,
    Save,
    RefreshGit,
    OpenDiff(usize),
}
